(()=>{
'use strict';
const SUPABASE_URL='https://ovwfqbcxsdfddnfdgopg.supabase.co',SUPABASE_KEY='sb_publishable_h5KpewMqq8xOyf6VqFymyg_pgQXB99p',SESSION_KEY='soxlo_messenger_session_v3';
const $=id=>document.getElementById(id);let session=null,targetId=null,isOwner=false,profile=null;
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function initials(n='?'){return String(n).trim().split(/\s+/).slice(0,2).map(x=>x[0]?.toUpperCase()||'').join('')||'?'}
function loadSession(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||sessionStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
async function refresh(){if(!session?.refresh_token)throw Error('Session expired.');const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refresh_token})}),d=await r.json();if(!r.ok)throw Error('Session expired.');d.expires_at=Math.floor(Date.now()/1000)+Number(d.expires_in||3600);session=d;localStorage.setItem(SESSION_KEY,JSON.stringify(d));return d}
async function headers(extra={}){if(!session?.access_token)throw Error('Sign in to Messenger first.');if(!session.expires_at||Date.now()/1000>Number(session.expires_at)-45)await refresh();return{apikey:SUPABASE_KEY,Authorization:`Bearer ${session.access_token}`,...extra}}
async function api(path,o={}){return fetch(`${SUPABASE_URL}${path}`,{...o,headers:await headers(o.headers||{}),cache:'no-store',credentials:'omit'})}
function avatar(data,name){const e=$('profileAvatar');if(data&&/^data:image\/(jpeg|png|webp);base64,/i.test(data))e.innerHTML=`<img src="${esc(data)}" alt="Profile photo">`;else e.textContent=initials(name)}function msg(t,type=''){const e=$('profileMessage');e.textContent=t||'';e.className='message '+type}function photoMsg(t,type=''){const e=$('photoMessage');if(e){e.textContent=t||'';e.className='message '+type}}
async function loadProfile(){const r=await api(`/rest/v1/messenger_profiles?select=id,display_name,bio,avatar_data&id=eq.${encodeURIComponent(targetId)}&limit=1`);if(!r.ok)throw Error('Could not load profile.');profile=(await r.json())?.[0];if(!profile)throw Error('Member profile not found.');$('profileName').textContent=profile.display_name;$('profileBio').textContent=profile.bio||'No bio yet.';avatar(profile.avatar_data,profile.display_name);if(isOwner){$('editSection').hidden=false;$('postForm').hidden=false;$('nameInput').value=profile.display_name;$('bioInput').value=profile.bio||''}}
async function saveProfile(){const display_name=$('nameInput').value.trim().slice(0,40),bio=$('bioInput').value.trim().slice(0,300);if(!display_name)return msg('Display name is required.','error');const r=await api(`/rest/v1/messenger_profiles?id=eq.${encodeURIComponent(session.user.id)}`,{method:'PATCH',headers:{'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify({display_name,bio})});if(!r.ok)return msg('Could not save profile.','error');profile=(await r.json())?.[0]||{...profile,display_name,bio};$('profileName').textContent=display_name;$('profileBio').textContent=bio||'No bio yet.';avatar(profile.avatar_data,display_name);msg('Profile saved.','success')}
function readPhoto(file){if(!file)return;if(!String(file.type).startsWith('image/'))return photoMsg('Please choose an image.','error');if(file.size>10*1024*1024)return photoMsg('Choose an image under 10 MB.','error');photoMsg('Preparing photo…');const fr=new FileReader();fr.onerror=()=>photoMsg('Could not read that photo.','error');fr.onload=()=>{const img=new Image();img.onerror=()=>photoMsg('Could not open that photo. Try another image.','error');img.onload=async()=>{try{const c=document.createElement('canvas'),size=256;c.width=c.height=size;const x=c.getContext('2d'),scale=Math.max(size/img.width,size/img.height),w=img.width*scale,h=img.height*scale;x.drawImage(img,(size-w)/2,(size-h)/2,w,h);await savePhoto(c.toDataURL('image/jpeg',.8))}catch(e){photoMsg('Could not prepare profile photo.','error')}};img.src=fr.result};fr.readAsDataURL(file)}
async function savePhoto(data){photoMsg(data?'Saving profile photo…':'Removing photo…');const r=await api(`/rest/v1/messenger_profiles?id=eq.${encodeURIComponent(session.user.id)}`,{method:'PATCH',headers:{'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify({avatar_data:data})});if(!r.ok){let detail='';try{detail=(await r.json())?.message||''}catch{}return photoMsg(detail||'Could not save profile photo.','error')}const rows=await r.json();profile={...profile,...(rows?.[0]||{}),avatar_data:data};avatar(data,profile.display_name);photoMsg(data?'Profile photo saved.':'Profile photo removed.','success')}
async function loadPosts(){try{const r=await api(`/rest/v1/messenger_daily_posts?select=id,user_id,body,created_at&user_id=eq.${encodeURIComponent(targetId)}&order=created_at.desc&limit=50`);if(!r.ok)throw Error();const rows=await r.json(),box=$('postsList');if(!rows.length){box.innerHTML='<div class="empty">No daily posts yet.</div>';return}box.innerHTML=rows.map(p=>`<article class="post"><div class="post-body">${esc(p.body)}</div><div class="post-meta"><span>${new Date(p.created_at).toLocaleString()}</span>${isOwner?`<button class="delete-post" data-delete="${esc(p.id)}" type="button">Delete</button>`:''}</div></article>`).join('');box.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deletePost(b.dataset.delete))}catch{$('postsList').innerHTML='<div class="empty">Posts are temporarily unavailable.</div>'}}
async function createPost(e){e.preventDefault();const body=$('postInput').value.trim();if(!body)return;const r=await api('/rest/v1/messenger_daily_posts',{method:'POST',headers:{'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify({user_id:session.user.id,body})});if(r.ok){$('postInput').value='';$('postCount').textContent='0 / 1000';loadPosts()}}
async function deletePost(id){const r=await api(`/rest/v1/messenger_daily_posts?id=eq.${encodeURIComponent(id)}&user_id=eq.${encodeURIComponent(session.user.id)}`,{method:'DELETE'});if(r.ok)loadPosts()}
async function boot(){try{session=loadSession();if(!session?.user?.id)throw Error('Please sign in to SOXLO Messenger first.');targetId=new URLSearchParams(location.search).get('id')||session.user.id;isOwner=targetId===session.user.id;await loadProfile();$('loadingCard').hidden=true;$('profileCard').hidden=false;loadPosts();if(isOwner){$('saveProfileBtn').onclick=saveProfile;$('choosePhotoBtn').onclick=()=>{photoMsg('');const input=$('photoInput');input.value='';input.click()};$('photoInput').onchange=e=>readPhoto(e.target.files?.[0]);$('removePhotoBtn').onclick=()=>savePhoto(null);$('postForm').onsubmit=createPost;$('postInput').oninput=e=>$('postCount').textContent=`${e.target.value.length} / 1000`}}catch(e){$('loadingCard').textContent=e.message||'Could not open profile.'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();