-- SOXLO Private Player setup
-- Run this in Supabase SQL Editor for the project used by supabase-config.json.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'member' check (role in ('member','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.special_tracks (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 120),
  storage_path text not null unique,
  uploaded_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.special_tracks enable row level security;

create or replace function public.is_soxlo_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

-- HARD MEMBERSHIP CAP: only two SOXLO Private Player login accounts may exist.
-- The advisory lock prevents simultaneous signups from slipping past the count.
create or replace function public.enforce_soxlo_account_limit()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  perform pg_advisory_xact_lock(83920501);
  if (select count(*) from auth.users) >= 2 then
    raise exception 'SOXLO private membership is full. Maximum 2 login accounts.';
  end if;
  return new;
end;
$$;

drop trigger if exists soxlo_limit_auth_users on auth.users;
create trigger soxlo_limit_auth_users
before insert on auth.users
for each row execute procedure public.enforce_soxlo_account_limit();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles(id, role) values(new.id, 'member')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

insert into public.profiles(id, role)
select id, 'member' from auth.users
on conflict (id) do nothing;

drop policy if exists "members can read own profile" on public.profiles;
create policy "members can read own profile"
on public.profiles for select
to authenticated
using (id = auth.uid());

drop policy if exists "members can read private tracks" on public.special_tracks;
create policy "members can read private tracks"
on public.special_tracks for select
to authenticated
using (true);

drop policy if exists "admins can insert private tracks" on public.special_tracks;
create policy "admins can insert private tracks"
on public.special_tracks for insert
to authenticated
with check (public.is_soxlo_admin());

drop policy if exists "admins can update private tracks" on public.special_tracks;
create policy "admins can update private tracks"
on public.special_tracks for update
to authenticated
using (public.is_soxlo_admin())
with check (public.is_soxlo_admin());

drop policy if exists "admins can delete private tracks" on public.special_tracks;
create policy "admins can delete private tracks"
on public.special_tracks for delete
to authenticated
using (public.is_soxlo_admin());

insert into storage.buckets(id, name, public)
values ('special-songs','special-songs',false)
on conflict (id) do update set public=false;

drop policy if exists "members can read special songs" on storage.objects;
create policy "members can read special songs"
on storage.objects for select
to authenticated
using (bucket_id='special-songs');

drop policy if exists "admins can upload special songs" on storage.objects;
create policy "admins can upload special songs"
on storage.objects for insert
to authenticated
with check (bucket_id='special-songs' and public.is_soxlo_admin());

drop policy if exists "admins can update special songs" on storage.objects;
create policy "admins can update special songs"
on storage.objects for update
to authenticated
using (bucket_id='special-songs' and public.is_soxlo_admin())
with check (bucket_id='special-songs' and public.is_soxlo_admin());

drop policy if exists "admins can delete special songs" on storage.objects;
create policy "admins can delete special songs"
on storage.objects for delete
to authenticated
using (bucket_id='special-songs' and public.is_soxlo_admin());

-- IMPORTANT OWNER STEP
-- After creating/signing in with your own Supabase Auth account, replace the email below
-- and run this one statement to unlock the upload panel for that account:
-- update public.profiles set role='admin'
-- where id=(select id from auth.users where email='YOUR-OWNER-EMAIL');
