plugins { id 'com.android.application' }

android {
    namespace 'com.soxlo.messenger'
    compileSdk 35

    defaultConfig {
        applicationId 'com.soxlo.messenger'
        minSdk 24
        targetSdk 35
        versionCode 2
        versionName '2.0'
    }

    buildTypes {
        debug {
            debuggable false
        }
    }
}
